### ISSUE TITLE
extracting pretrained model

### ISSUE THREAD

**Issue by chandnikathuria1992** [jeffreyhuang1/two-stream-action-recognition#12]
Tried to extract pretrained model using tar...but its giving error: 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: A lone zero block at 79811
tar: Exiting with failure status due to previous errors
Any idea?

**Comment by jeffreyhuang1** [comment]
Hi,
Please refer the following parts of my code to load the pretrained  model !!

https://github.com/jeffreyhuang1/two-stream-action-recognition/blob/master/spatial_cnn.py#L85

Jeffrey
