### ISSUE TITLE
About  spatial cnn,how many images do you extract from every trainning video? thank you ! 

### ISSUE THREAD

**Issue by VictorLeeLk** [jeffreyhuang1/two-stream-action-recognition#14]
About  spatial cnn,how many images do you extract from every trainning video? thank you !

**Comment by jeffreyhuang1** [comment]
Hi,

Sorry for the late reply !! For every videos in a mini-batch, we randomly select 3 frames from each video. Then a consensus among the frames will be derived as the video-level prediction for calculating categorical cross entropy  loss.

Jeffrey
