### ISSUE TITLE
Motion resent101

### ISSUE THREAD

**Issue by LiliMeng** [jeffreyhuang1/two-stream-action-recognition#15]
Hi, 
         Thanks a lot for providing the open-source code!

         May I ask how did you get your pre-trained motion ResNet101? It's pre-trained on ImageNet and fine-tuned on UCF101 or the just changing the channels of the model trained on ImageNet? 
      
          Highly appreciate your time and help!

**Comment by jeffrey-umbo** [comment]
Hi,
I utilize the cross-modality pretraining technique to transfer the weight of model pretrained on ImageNet to fit the motion ResNet101. The details are described in Readme!

Sincerely,
Jeffrey

**Comment by jeffreyhuang1** [comment]
Hi,
Thanks for the good question!! I utilize the cross-modality pretraining technique to transfer the model weight pretrained on ImageNet to fit the motion ResNet101. The details are described in Readme!

Sincerely,
Jeffrey

**Comment by LiliMeng** [comment]
Hi Jeffrey,
 
           Thanks a lot for your kind and quick reply. The channels in the RGB and optical flow stream are different, how did you fit the pre-trained ImageNet model to the optical flow stream? Do you have the code to load the ImageNet pre-trained model to optical flow stream? 

           Highly appreciate your time and help!

**Comment by jeffreyhuang1** [comment]
Hi,
Please refer the link below to see my implementation details of cross-modality pretraining method!

https://github.com/jeffreyhuang1/two-stream-action-recognition/blob/master/network.py#L216

Jeffrey

**Comment by LiliMeng** [comment]
Great! Thanks a lot!
