### ISSUE TITLE
About Spatialcnn

### ISSUE THREAD

**Issue by hareeshdevarakonda** [jeffreyhuang1/two-stream-action-recognition#18]
on what basis you are only taking 3 random frames per video for video-level prediction?

Could you please justify this I just want to know whats the reason behind this if you could let me, that would be great

Thanks
Hareesh

**Comment by jeffreyhuang1** [comment]
Hi,
Sorry for the late reply,

My training method of spatial stream follows the strategy in [TSN](https://link.springer.com/chapter/10.1007/978-3-319-46484-8_2). You can refer this paper for the details you need.

Jeffrey
