### ISSUE TITLE
 a problem of ‘ValueError: insecure string pickle’

### ISSUE THREAD

**Issue by ttthappy** [jeffreyhuang1/two-stream-action-recognition#21]
Thank you for your kindly sharing this code. But I have a problem of ‘ValueError: insecure string pickle’, when run the flowing codes in spatial_dataloader and motion_dataloader,
with open('dic/frame_count.pickle', 'rb') as file:
            dic_frame = pickle.load(file)
I installed the Anaconda2-4.1.1-Linux-x86_64. Is the version too low? 
I tried to modify 'rb' to 'r', but still the same problem. Can you help me? Thank you!

**Comment by jeffreyhuang1** [comment]
What is your numpy version?  According to this [link](https://github.com/numpy/numpy/issues/4879). It might be caused by the version mismatch between encoding and decoding.

Maybe your can try to re-generate the pickle file with my code and test in again?

Jeffrey

**Comment by ttthappy** [comment]
Thank  you very much ! I modified to import cPickle as pickle,ok
