### ISSUE TITLE
Thank you for your kindly sharing this great code . I was puzzled about some details

### ISSUE THREAD

**Issue by ttthappy** [jeffreyhuang1/two-stream-action-recognition#24]
Dear Jeffrey,
    Thank you for your kindly sharing the great two-stream-action-recognition code. Though I have read the readme and reference papers[1] [2] [3], I was puzzled about some details.
In training strategies, in every mini-batch, you randomly select 64 (batch size) videos from 9537 training videos and further randomly select 1 stacked optical flow in each video. I wonder which paper this method was proposed. Is this method part of TSN paper[2]?
     In testing method, for every 3783 testing videos, we uniformly sample 19 frames in each video and the video level prediction is the voting result of all 19 frame level predictions. This method seems like TSN[2], but the 19 segments of 10 frames maybe overlapped. 
     In your validation stage, the precision stored in opf_test.csv is the test precision or validation precision? The loaded data is the testlist01?  
     The motion_video_preds.pickle save the video level prediction. What does it mean? And where to find the test accuracy in split 1 testlist01?
    Is this code corresponding to your own paper? I want to quote your paper. Or can you give me some details about your code? Thank you very much.
    I send an E-mail for your help. Thank you very much.
Best Regard,
tangjun

**Comment by ttthappy** [comment]
Dear Jeffrey,
    Thank you for your kindly sharing the great two-stream-action-recognition code. Though I have read the readme and reference papers[1] [2] [3], I was puzzled about some details.
    In training strategies, in every mini-batch, you randomly select 64 (batch size) videos from 9537 training videos and further randomly select 1 stacked optical flow in each video. I wonder which paper this method was proposed. Is this method part of TSN paper[2]?
   In testing method, for every 3783 testing videos, we uniformly sample 19 frames in each video and the video level prediction is the voting result of all 19 frame level predictions. This method seems like TSN[2], but the 19 segments of 10 frames maybe overlapped. 
   Is this code corresponding to your own paper? I want to quote your paper. Or can you give me some details about your code? Thank you very much.
   I send an E-mail for your help. Thank you very much.
Best Regard,
tangjun

**Comment by jeffreyhuang1** [comment]
Hi tangjun,

Sorry for the late reply!

Basically, the implementation in my repo is the combination of the three papers that I mentioned in my Readme.

For the spatial stream, I  followed the method in TSN [2] but I did not implement the corner cropping.

For the motion stream, I implemented  the method in two-stream CNN [1].

And for the testing method, for the reason that some videos in UCF101 dataset contain less than 25 frame, which is the testing method in [1], I set the number of testing frames as the number of minimum number of frames of single video in UCF101 dataset, which is 19.

Finally, the implementation in this repo is not corresponding to my own paper. It is just the combination of some previous works.
If you would like to quote this repo, I think you can just quote the [1][2][3] in my readme!.

Best regards,
Jeffrey

**Comment by ttthappy** [comment]
Hi Jeffrey,
Thank you for your kindly help! I’m new to deep learning. So I still puzzled about that，in your validation stage, the precision stored in opf_test.csv is the test precision or validation precision? The loaded data is the testlist01? And where to find the test accuracy in split 1 testlist01?
Best Regard,
tangjun

**Comment by ttthappy** [comment]
I got it. Thank you for your kindly help!
Best Regard,
tangjun
