### ISSUE TITLE
For spatial_cnn.py,When predict the test dataset,why not use tsn network to predict it's class?

### ISSUE THREAD

**Issue by VictorLeeLk** [jeffreyhuang1/two-stream-action-recognition#26]
Hello,
      I get some confusion about reading spatial_cnn.py.When predict the test dataset,I find that you just add all sample's predictions to be the final result ,why not use tsn network to predict it's class? for example ,every video is divied to 3 segements,and randly choose one RGB frame to predict ,  then average the three predictions as the final result!

 for j in range(nb_data):
                videoName = keys[j].split('/',1)[0]
                if videoName not in self.dic_video_level_preds.keys():
                    self.dic_video_level_preds[videoName] = preds[j,:]
                else:
                    self.dic_video_level_preds[videoName] += preds[j,:]

**Comment by jeffreyhuang1** [comment]
Hi,

This testing method completely followed the method in TSN. Please refer the paper for more details!

Jeffrey

**Comment by VictorLeeLk** [comment]
got it.Thank you very much!
