### ISSUE TITLE
j - 1 in flow index

### ISSUE THREAD

**Issue by newpro** [jeffreyhuang1/two-stream-action-recognition#28]
Hey @jeffreyhuang1 
Thanks very much for your work! It really help me understand the papers.

I am not sure if i understand this part right. In function [stackopf](https://github.com/jeffreyhuang1/two-stream-action-recognition/blob/master/dataloader/motion_dataloader.py#L55), should it be j instead of j-1? E.g:
```python
flow[2*(j),:,:] = H
flow[2*(j)+1,:,:] = V
```

Thanks!

**Comment by kasparov92** [comment]
I came across the same issue, it is not yet changed in the main code. 
@newpro, I would like to know if you got similar accuracy and how much did this affect the accuracy?
