### ISSUE TITLE
How to get pickle files?

### ISSUE THREAD

**Issue by RZJM** [jeffreyhuang1/two-stream-action-recognition#3]
Hi:
    After I run python UCF_spatial_cnn.py , then I get "can not find pickle" error ,how to get pickle files?

**Comment by jeffreyhuang1** [comment]
Hi:
The "dic_training.pickle" file contains every training frames path, which is **dic[path_to_training_frames] = video_label** 
which might be different on your device. So, maybe you might generate the pickle file based on the UCF rgb data on your device. Just make sure the output of dataloader is the frames your want !!

Regards,
Jeffrey

**Comment by RZJM** [comment]
Get that, thanks!
