### ISSUE TITLE
missing 'frame_count.pickle'

### ISSUE THREAD

**Issue by LiJunnan1992** [jeffreyhuang1/two-stream-action-recognition#30]

**Comment by ice-pice** [comment]
Is there a code to directly generate this pickle file or download link?

**Comment by ice-pice** [comment]
Ok. I got it working. For others, I use the below script.
```
data_dir = 'jpegs_256/'
all_videos_dir = os.listdir(data_dir);
dic = {};
total_sum = 0;

for curr_video in all_videos_dir:
        num_frames = len(os.listdir(os.path.join(data_dir, curr_video)));
        dic[curr_video] = num_frames-1;
        total_sum += num_frames;
pdb.set_trace()
pickle.dump(dic, open('frame_count.pickle','wb'))
```

**Comment by kasparov92** [comment]
@ice-pice, the code you have used is wrong, it is needed the number of frames per video-clip and not the number of videos per class. Here is the right code:

    def generate_frame_count(self):
        all_videos_dir = os.listdir(self.data_path); 
        dic = {};

        for curr_category in all_videos_dir:
            curr_dir = os.path.join(self.data_path, curr_category)

            for video in  os.listdir(curr_dir):
                num_frames = len(os.listdir(os.path.join(curr_dir, video)));
                dic[video] = num_frames;
    def load_frame_count(self):
        #print '==> Loading frame number of each video'
        pickle_path = 'dataloader/dic/frame_count.pickle'
        if not os.path.exists(pickle_path):
            self.generate_frame_count()

        with open(pickle_path,'rb') as file:
            dic_frame = pickle.load(file)
        file.close()

        for line in dic_frame :
            videoname = line.split('_',1)[1].split('.',1)[0]
            n,g = videoname.split('_',1)
            if n == 'HandStandPushups':
                videoname = 'HandstandPushups_'+ g
            self.frame_count[videoname]=dic_frame[line]
