### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by panna19951227** [jeffreyhuang1/two-stream-action-recognition#31]
I have been meeting a problem as follows,can you give me some advice?thanks!
![1231](https://user-images.githubusercontent.com/39176743/41135303-87a5ac0a-6b03-11e8-8396-ce720a130db1.PNG)

**Comment by jeffreyhuang1** [comment]
Hi,

I think you might run this code under python3. 
Please try to run it with under python2!

Thanks,
Jeffrey
