### ISSUE TITLE
the dataset of flow  are damaged files

### ISSUE THREAD

**Issue by Tylerjoe** [jeffreyhuang1/two-stream-action-recognition#32]
can you upload the dataset again, thanks

**Comment by jeffreyhuang1** [comment]
Hi,

I download the extracted rgb frames and optical flow images from this [repo](https://github.com/feichtenhofer/twostreamfusion). If this link is broken, you might need to download the original videos of UCF101 and extract the rgb and optical flow images manually.

Jeffrey
