### ISSUE TITLE
UCF_101 is not defined

### ISSUE THREAD

**Issue by sunnydps32** [jeffreyhuang1/two-stream-action-recognition#33]
The following error occurs :-

Traceback (most recent call last):
  File "average_fusion.py", line 23, in <module>
    ucf_split='01')
  File "D:\IP\SignLanguage\TwoStreamFusion\two-stream-action-recognition-master\
dataloader\spatial_dataloader.py", line 78, in __init__
    splitter = UCF101_splitter(path=ucf_list,split=ucf_split)
NameError: name 'UCF101_splitter' is not defined

Also, please specify the directories inside the 'UCF101' folder.

**Comment by jeffreyhuang1** [comment]
Hi,

For the first issue, this code is implemented by python2.7. I am wondering if you run this code under python3, which might be a possible reason for this error.

For the second issue, the directories inside the 'UCF101' folder can be downloaded via the reference in my readme.

Jeffrey
