### ISSUE TITLE
UCF101_splitter not defined

### ISSUE THREAD

**Issue by sunnydps32** [jeffreyhuang1/two-stream-action-recognition#34]
The function UCF101_splitter is not defined anywhere.
The following error is shown on running average_fusion.py

splitter = UCF101_splitter(path=ucf_list,split=ucf_split)
NameError: name 'UCF101_splitter' is not defined

**Comment by jeffreyhuang1** [comment]
Hi,

I do define UCF101_splitter in [dataloader/split_train_test_video.py](https://github.com/jeffreyhuang1/two-stream-action-recognition/blob/master/dataloader/split_train_test_video.py)

Jeffrey
