### ISSUE TITLE
the problem of the pre-trained model

### ISSUE THREAD

**Issue by Tylerjoe** [jeffreyhuang1/two-stream-action-recognition#37]
I download the pre-trained model ( model_best.pth.tar), but it's damaged. So ,can I download the pre-trained model from other places? Thanks

**Comment by jeffreyhuang1** [comment]
Hi, 
I am curious about how you extract the pretrained model, since the correct way to load the pretrained model is via the function torch.load().

Maybe you could try this method! If it is still broken, please feel free to let me know!! I will try to re-upload it.

Jeffrey

**Comment by jeffreyhuang1** [comment]
@Tylerjoe  No problem :)
