### ISSUE TITLE
How to run this code?

### ISSUE THREAD

**Issue by LiliMeng** [jeffreyhuang1/two-stream-action-recognition#5]
Hi, Thanks a lot for sharing this code!

May I ask how to start to train your two-stream network and how to pre-process data? 

Thanks a lot!

**Comment by jeffreyhuang1** [comment]
Hi, I will update this repo at about Dec 20 to make it more user-friendly. Maybe you can start from downloading the UCF101 dataset and generating your RGB frames and optical flow data, or you can just download the released preprocessed data from [twostreamfusion](https://github.com/feichtenhofer/twostreamfusion)

Jeffrey
