### ISSUE TITLE
Recognizing activity realtime

### ISSUE THREAD

**Issue by Zumbalamambo** [jeffreyhuang1/two-stream-action-recognition#8]
Can you please share the pretrained model and testing code? Im having hard time while trying to extracting the rgb frames and compute optical flow for activity recognition... Thank you

**Comment by jeffreyhuang1** [comment]
Hi
Since I am currently busying on some projects, I will probably try to implement the realtime testing code a few weeks later.
The pretrained model is shared on my google drive. Please refer my README.md

Jeffrey

**Comment by mariankyoussef** [comment]
Did anyone try to download the pretrained models from google drives? Because they are corrupted.
